name: Build ZMK Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install West & Initialize ZMK
      run: |
        pip install west
        rm -rf .west
        west init -m https://github.com/zmkfirmware/zmk.git --mr main --mf app/west.yml
        west update
        pip install pyelftools intelhex

    - name: Build Left
      run: |
        west build -s . -d build/left -b seeeduino_xiao_ble -- \
          -DZMK_CONFIG=config \
          -DSHIELD=corne_left \
          -DZMK_EXTRA_MODULES=. \
          -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

    - name: Build Right
      run: |
        west build -s . -d build/right -b seeeduino_xiao_ble -- \
          -DZMK_CONFIG=config \
          -DSHIELD=corne_right \
          -DZMK_EXTRA_MODULES=. \
          -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

    - name: Build Dongle (Central)
      run: |
        west build -s . -d build/central -b seeeduino_xiao_ble -- \
          -DZMK_CONFIG=config \
          -DSHIELD=corne_right \
          -DZMK_EXTRA_MODULES=. \
          -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

    - name: Upload Left Firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-left
        path: build/left/zephyr/zmk.uf2

    - name: Upload Right Firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-right
        path: build/right/zephyr/zmk.uf2

    - name: Upload Dongle Firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-central
        path: build/central/zephyr/zmk.uf2
