name: Build ZMK Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zmkfirmware/zmk-dev-arm:stable

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Left
      run: |
        west init -l config
        west update
        west build -s zmk/app -d build/left -b seeeduino_xiao_ble -- \
          -DZMK_CONFIG=config \
          -DSHIELD=corne_left \
          -DZMK_EXTRA_MODULES=. \
          -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

    - name: Build Right
      run: |
        west build -s zmk/app -d build/right -b seeeduino_xiao_ble -- \
          -DZMK_CONFIG=config \
          -DSHIELD=corne_right \
          -DZMK_EXTRA_MODULES=. \
          -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

    - name: Build Dongle (Central)
      run: |
        west build -s zmk/app -d build/central -b seeeduino_xiao_ble -- \
          -DZMK_CONFIG=config \
          -DSHIELD=corne_right \
          -DZMK_EXTRA_MODULES=. \
          -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

    - name: Upload Left Firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-left
        path: build/left/zephyr/zmk.uf2

    - name: Upload Right Firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-right
        path: build/right/zephyr/zmk.uf2

    - name: Upload Dongle Firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-central
        path: build/central/zephyr/zmk.uf2
